### ISSUE TITLE
Cannot run spek tests with latest IntelliJ 2016.3 EAP

### ISSUE THREAD

**Issue by jmeeks** [raniejade/spek-idea-plugin#20] opened 2016-10-30 16:28 UTC
Intellij version

```
IntelliJ IDEA 2016.3 EAP
Build #IU-163.6957.12, built on October 25, 2016
IntelliJ IDEA EAP User
Expiration date: November 24, 2016
JRE: 1.8.0_112-release-b408 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Kotlin version: `1.0.4`
Spek plugin version: `0.2.5`
Spek version: `1.0.89`

I ran Spek tests from the left-rail shortcut in the editor view. With the latest IntelliJ EAP for 2016.3 -- but not the previous 2016.3 EAP -- I get the following error:

```
org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
java.lang.IllegalAccessError: org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
    at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
    at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
    at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
    at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
    at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
    at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
    at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
    at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
    at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mosi0815** [comment] 2016-11-23 17:57
Same with the final version:

`null
java.lang.IllegalAccessError
	at sun.misc.Unsafe.throwIllegalAccessError(Unsafe.java:1142)
	at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
	at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
	at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
	at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
	at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by sblundy** [comment] 2016-11-23 18:34
I'm seeing the same problem, but I get a different exception with the existing config. I press run and nothing would happen. IntelliJ's exception dialog just popped up. The tests have worked previously and run when I execute the gradle test task. Deleting the config and running anew resulted in a different exception.

### Environment

Spek plugin: 0.2.5
Kotlin version: 1.0.3

> IntelliJ IDEA 2016.3
> Build #IU-163.7743.44, built on November 17, 2016
> ...
> JRE: 1.8.0_112-release-408-b2 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### Exception when I ran an existing run config
<pre>org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
java.lang.IllegalAccessError: org.jetbrains.spek.idea.SpekRunConfiguration.getSearchScope()Lcom/intellij/psi/search/GlobalSearchScope;
	at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
	at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
	at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
	at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
	at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</pre>

### Exception on new run config
<pre>null
java.lang.IllegalAccessError
	at sun.misc.Unsafe.throwIllegalAccessError(Unsafe.java:1142)
	at com.intellij.execution.configurations.SearchScopeProvider.createSearchScope(SearchScopeProvider.java:32)
	at com.intellij.execution.configurations.CommandLineState.<init>(CommandLineState.java:55)
	at com.intellij.execution.configurations.JavaCommandLineState.<init>(JavaCommandLineState.java:28)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.<init>(BaseJavaApplicationCommandLineState.java:39)
	at org.jetbrains.spek.idea.SpekRunConfiguration$getState$1.<init>(SpekRunConfiguration.kt:101)
	at org.jetbrains.spek.idea.SpekRunConfiguration.getState(SpekRunConfiguration.kt:101)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:530)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</pre>

**Comment by rapasoft** [comment] 2016-11-23 21:43
This issue has been sitting here for more than 20 days. I don't know how supported is this "official Intellij IDEA plugin", but it's a pity that I had to rewrite all of my Speks to unit tests a day before workshop on which I wanted to present Spek as a nice alternative.

😢

**Comment by mosi0815** [comment] 2016-11-23 22:00
You are right. I also started to use Spek for a small project. I quite like it. But now I have to rewrite 40 test cases to junit. Sure I can run them through Gradle but that's not really convenient.

**Comment by sblundy** [comment] 2016-11-24 01:14
And this looks like it's a duplicate of #12

**Comment by raniejade** [comment] 2016-11-24 02:34
Hey guys, sorry been busy with work lately. Just finishing up some tasks, will look into it after that.

**Closed** 2016-11-24 15:27 UTC

**Comment by raniejade** [comment] 2016-11-24 16:25
@here I released version `v0.2.6` which include the fix provided by @sblundy . Please update and let me know if you experience any problem. (it might take awhile before IDEA to take notice of the new build)

**Comment by sblundy** [comment] 2016-11-24 19:35
Thanks @raniejade! Updated and it works fine

**Comment by rapasoft** [comment] 2016-11-24 20:55
Thank you, it works :)

Sorry for my rant, but as a Kotlin enthusiast I was really disappointed that I had to rewrite the tests to JUnit and then explain this to a group of people at the workshop. Timing was really bad :(
